name: SSH Access to GitHub Actions Runner

on: workflow_dispatch  # Executa manualment

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Installa ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Autentica ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Obre el túnel SSH
        run: |
          nohup ngrok tcp 22 --log=stdout > ngrok.log &
          sleep 10
          curl -s localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url"

      - name: Mostra les credencials SSH
        run: |
          echo "Usuari: runner"
          echo "IP/Puerto: $(curl -s localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url" | sed 's/tcp:\/\///')"
          echo "Connecta't amb: ssh runner@<IP> -p <Port>"
